# Hyprlock config
# Not used with DMS, but this one looks good :)

general {
    grace = 1
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/wall.jpg
    # see https://wiki.hyprland.org/Configuring/Variables/#blur
    blur_size = 2
    blur_passes = 1 # 0 disables blur
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 #  absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(167, 0, 0, 1)
    inner_color = rgba(0, 0, 0, 0.4)
    font_color = rgba(227, 168, 71, 0.8)
    font_family = JetBrainsMono Nerd Font ExtraBold
    fade_on_empty = false
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 100
    capslock_color = rgba(227, 168, 71, 0.8)
    numlock_color = rgba(227, 168, 71, 0.8)
    bothlock_color = rgba(227, 168, 71, 0.8)
    placeholder_text = <i><span foreground="##ffffff99">🔒 Enter Password</span></i>
    hide_input = false
    position = 0, 185
    halign = center
    valign = bottom
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
    color = rgba(227, 168, 71, 0.92)
    font_size = 24
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -60
    halign = center
    valign = top
}

# Hours-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
#    text = cmd[update:1000] echo "$(date +"%I")" #AM/PM
	color = rgba(185, 163, 163, 0.83)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold 
    position = 0, -110
    halign = center
    valign = top
}

# Seconds-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = rgba(186, 113, 113, 0.8)
    font_size = 60
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 5, -275
    halign = center
    valign = top
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(185, 163, 163, 0.83)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -325
    halign = center
    valign = top
}

# Picture of choice.
image {
    monitor =
    path = ~/Pictures/Wallpapers/wall.jpg
    size = 200
    rounding = -1
    border_size = 0
    border_color = red
    rotate = 0
    reload_time = -1
    position = 0, 350
    halign = center
    valign = bottom
}

# Username
label {
    monitor =
    text =    $USER
    color = rgba(255, 249, 234, 0.95)
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 24
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 100
    halign = center
    valign = bottom
}

# Uptime
label {
    monitor =
    text = cmd[update:60000] echo "<b> "$(uptime -p)" </b>"
    color = rgba(255, 0, 0, 1)
    font_size = 12
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 0
    halign = right
    valign = bottom
}