# Environment Variables
# See https://wiki.hyprland.org/Configuring/Environment-variables/

# === Defaults === #
env = TERMINAL,kitty
env = EDITOR,micro
env = VISUAL,micro

# ==== Cursor settings ==== # 
env = HYPRCURSOR_THEME,Furina
env = XCURSOR_THEME,Furina
env = XCURSOR_SIZE,30
env = HYPRCURSOR_SIZE,30

# ==== GDK Backends ==== #
env = GDK_SCALE,1.0
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# ==== XDG Desktop Portal ==== #
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# ==== QT configuration ==== # 
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct   
env = QT_QUICK_CONTROLS_STYLE,org.hyprland.style
env = QT_QPA_PLATFORMTHEME,qt6ct

# ==== Mozilla/Firefox ==== #
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_DBUS_REMOTE=1      # For shared clipboard with Xwayland apps
env = EGL_PLATFORM,wayland

# === Fix electron apps flickering ==== #
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# ==== FOR VM and POSSIBLY NVIDIA ==== #
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = _JAVA_AWT_WM_NONREPARENTING=1

# https://gist.github.com/kRHYME7/1d2574e8f3a4b7ad4059535503ce1eaa
env = LIBVA_DRIVER_NAME,iHD
env = __GLX_VENDOR_LIBRARY_NAME,mesa
env = WLR_RENDERER,gles2
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = GBM_BACKEND,dri
env = WLR_DRM_NO_MODIFIERS,1
env = __GL_VRR_ALLOWED,0

# ==== NVIDIA ONLY ==== #
# env = LIBVA_DRIVER_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = __GL_GSYNC_ALLOWED,1
# env = __NV_PRIME_RENDER_OFFLOAD,1
# env = __VK_LAYER_NV_optimus,NVIDIA_only
# env = NVD_BACKEND,direct