# Enviroment variables

# === Game tags === #
windowrule = tag +games, match:class ^(gamescope)$
windowrule = tag +games, match:class ^(steam_app_\d+)$

# === Gamestore tags === #
windowrule = tag +gamestore, match:class ^([Ss]team)$
windowrule = tag +gamestore, match:title ^([Ll]utris)$
windowrule = tag +gamestore, match:class ^(com.heroicgameslauncher.hgl)$

# === Workspaces Rules === #
windowrule = fullscreen on, match:title (Honkai: Star Rail)
windowrule = fullscreen on, match:title (Zenless Zone Zero)
windowrule = fullscreen on, match:title (Genshin Impact)

windowrule = float on, match:class (moe.launcher.the-honkers-railway-launcher), match:title ^(The Honkers Railway Launcher)$