$mainMod = SUPER
$fileManager = thunar
$browser = DRI_PRIME=0 zen-browser
$scripts = /home/kurami/.config/hypr/scripts
$AndroidST= prime-run android-studio

# Reload Hyprland configuration
bind = $mainMod CTRL, R, exec, hyprctl reload

# Open Android Studio
bind = $mainMod SHIFT, H, exec, $AndroidST

# Shortcuts
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, $browser

# Color Selection - Hyprpicker
bind = $mainMod SHIFT, P, exec, hyprpicker -a / –autocopy
bind = $mainMod SHIFT, E, exec, $scripts/RofiEmoji.sh # emoji menu
