# === Hyprland Configuration === #
# See https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/configs/Monitors.conf     # MONITOR CONFIG
source = ~/.config/hypr/configs/Startup.conf      # STARTUP
source = ~/.config/hypr/configs/InputDevices.conf # INPUT CONFIG
source = ~/.config/hypr/configs/WindowsLook.conf  # GENERAL LAYOUT & DECORATIONS
source = ~/.config/hypr/configs/Animations.conf   # ANIMATIONS
source = ~/.config/hypr/configs/ENVariables.conf  # ENVIRONMENT VARIABLES
source = ~/.config/hypr/configs/Misc.conf         # MISC CONFIGS
source = ~/.config/hypr/configs/WindowsRules.conf # WINDOW RULES
source = ~/.config/hypr/configs/GameRules.conf    # GAME RULES

# === DMS generated config files === #
source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf

source = ~/.config/hypr/configs/Keybinds.conf     # Custom keybinds to launch apps